blog/models/__init__.py
from .user import *
from .setting import *
from .post import *

blog/models/post.py
from arrow import arrow

from .. import db


__all__ = ["Post", "Tag", "Category"]


association_table_for_posts_and_tags = db.Table(
    "association_posts_tags",
    db.Model.metadata,
    db.Column("post_id", db.Integer, db.ForeignKey("posts.id")),
    db.Column("tag_id", db.Integer, db.ForeignKey("tags.id"))
)


class Post(db.Model):
    __tablename__ = "posts"

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(200), nullable=False)
    content = db.Column(db.Text)

    deleted = db.Column(db.Boolean, default=False)

    category = db.Column(db.Integer, db.ForeignKey("categories.id"))
    tags = db.relationship("Tag",
                           secondary=association_table_for_posts_and_tags,
                           backref="posts")

    time_created = db.Column(db.DateTime(timezone=True), default=arrow.Arrow.now().datetime)
    time_modified = db.Column(db.DateTime(timezone=True), default=arrow.Arrow.now().datetime)

    @classmethod
    def query_page_of_posts(cls, limit=25, skip=0, tags=None, category=None):
        q = db.session.query(Post).filter(Post.deleted == False)

        if category:
            q = q.filter(Post.category == category)

        if tags:
            q = q.filter(Post.tags.any(Tag.id.in_(tags)))

        q = q.slice(skip, skip + limit)

        return q.all()

    @classmethod
    def query_one_post(cls, post_id):
        q = db.session.query(Post).filter(Post.deleted == False, Post.id == post_id).one()

        return q

    @classmethod
    def new_post(cls, title, content, **kwargs):
        post = Post(title=title,
                    content=content)
        db.session.add(post)

        db.session.commit()

    @classmethod
    def total_pages(cls, posts_per_page=25):
        q = db.session.query(Post).filter(Post.deleted == False)

        return q.count() / posts_per_page + 1


class Tag(db.Model):
    __tablename__ = "tags"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(200), nullable=False)


class Category(db.Model):
    __tablename__ = "categories"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(200), nullable=False)

blog/models/setting.py
from sqlalchemy.orm.exc import NoResultFound

from .. import db

SETTING_BLOG_NAME = 1


class Setting(db.Model):
    __tablename__ = "settings"

    id = db.Column(db.Integer, primary_key=True)
    value = db.Column(db.Text(), nullable=False)
    extra = db.Column(db.Text())

    @classmethod
    def apply_setting(cls, id, value=None, extra=None):
        try:
            setting = db.session.query(Setting).filter(Setting.id == id).one()
            setting.value = value
            setting.extra = extra
        except NoResultFound:
            setting = Setting(id=id, value=value, extra=extra)
            db.session.add(setting)

        db.session.commit()
        return True

    @classmethod
    def load_settings(cls, id_list):
        settings = db.session.query(Setting).filter(Setting.id.in_(id_list)).all()
        return dict([(s.id, (s.value, s.extra)) for s in settings])

blog/models/user.py
from arrow import arrow
from datetime import datetime
from werkzeug.security import (generate_password_hash,
                               check_password_hash)

from flask.ext.login import UserMixin

from .. import db, login_manager


__all__ = ["User"]


class User(UserMixin, db.Model):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), nullable=False, unique=True, index=True)
    username = db.Column(db.String(64), nullable=False, unique=True, index=True)
    password_hash = db.Column(db.String(128))
    name = db.Column(db.String(64))

    @property
    def password(self):
        raise AttributeError("password is not a readable attribute")

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

blog/control_panel/forms.py
from flask.ext.wtf import Form
from wtforms import (StringField,
                     PasswordField,
                     BooleanField,
                     SubmitField,
                     TextAreaField
                     )
from wtforms.validators import (Required,
                                Length,
                                Email
                                )


class SetupForm(Form):
    blog_name = StringField("Blog Name", validators=[Required()])
    submit = SubmitField("Finish!")


class LoginForm(Form):
    email = StringField("Email", validators=[Required(), Length(1, 64), Email()])
    password = PasswordField("Password", validators=[Required()])
    remember_me = BooleanField("Keep me logged in")
    submit = SubmitField("Login")


class NewPostForm(Form):
    title = StringField("Title", validators=[Required()])
    body = TextAreaField("Body")
    draft = SubmitField("Save as Draft")
    post = SubmitField("Post")

blog/__init__.py
from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.login import LoginManager

from config import config


bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.login_view = "control_panel.login"


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    from .blogs import blogs as blogs_blueprint
    app.register_blueprint(blogs_blueprint)

    from .control_panel import control_panel as control_panel_blueprint
    app.register_blueprint(control_panel_blueprint)

    return app

blog/blogs/__init__.py
from flask import Blueprint

blogs = Blueprint("blogs", __name__)

from . import routes

blog/blogs/routes.py
from flask import (render_template,
                   redirect,
                   url_for,
                   request
                   )
from sqlalchemy.orm.exc import (
    NoResultFound,
)

from . import blogs
from ..models.post import Post
from ..utils import (load_page_meta,
                     NotSetup,
                     )
from ..post_body_parser import (
    parse,
)


@blogs.route("/")
def home():
    posts = Post.query_page_of_posts()
    return render_template("blogs/index.html",
                           posts=posts,
                           page_num=1,
                           page_total=Post.total_pages())


@blogs.route("/terminal")
def dev_terminal():
    raise


@blogs.route("/posts", methods=["GET"])
def post_list():
    # Get Page Num from query string
    try:
        page_num = int(request.args.get("page", 1))
    except ValueError:
        page_num = 1

    # Get tags and category filter
    tags = request.args.get("tags", None)
    if tags: tags = tags.split(",")
    category = request.args.get("category", "")

    posts = Post.query_page_of_posts(skip=(page_num - 1) * 25,
                                     limit=25,
                                     tags=tags,
                                     category=category)

    return render_template("blogs/index.html",
                           posts=posts,
                           page_num=page_num,
                           page_total=Post.total_pages())


@blogs.route("/post/<int:post_id>", methods=["GET"])
def post(post_id):
    is_raw = request.args.get("raw", 0) == 1

    try:
        post = Post.query_one_post(post_id)
    except NoResultFound:
        return "Not Found", 404

    if not is_raw:
        post_body = parse(post.content)

    return render_template("blogs/post.html",
                           post=post,
                           post_body=post_body)

blog/control_panel/__init__.py
from flask import Blueprint, url_for, redirect

control_panel = Blueprint("control_panel", __name__)

from ..utils import need_setup
from . import routes

blog/control_panel/routes.py
from flask import (render_template,
                   redirect,
                   url_for,
                   flash,
                   request
                   )
from flask.ext.login import (login_user,
                             logout_user,
                             login_required
                             )

from ..models import (User,
                      Post,
                      )

from . import control_panel
from .forms import (SetupForm,
                    LoginForm,
                    NewPostForm
                    )


@control_panel.route("/cpanel")
@login_required
def index():
    posts = Post.query_page_of_posts()
    return render_template("control_panel/index.html",
                           posts=posts,
                           page_num=1,
                           page_total=Post.total_pages(),
                           )


@control_panel.route("/cpanel/posts")
@login_required
def post_list():
    # Get Page Num from query string
    try:
        page_num = int(request.args.get("page", 1))
    except ValueError:
        page_num = 1

    # Get tags and category filter
    tags = request.args.get("tags", None)
    if tags: tags = tags.split(",")
    category = request.args.get("category", "")

    posts = Post.query_page_of_posts(skip=(page_num - 1) * 25,
                                     limit=25,
                                     tags=tags,
                                     category=category)

    return render_template("control_panel/index.html",
                           posts=posts,
                           page_num=page_num,
                           page_total=Post.total_pages())


@control_panel.route("/cpanel/newpost", methods=["GET", "POST"])
@login_required
def new_post():
    form = NewPostForm()
    if form.validate_on_submit():
        title = form.title.data
        content = form.body.data
        Post.new_post(title=title, content=content)
        return redirect(url_for("control_panel.index"))
    return render_template("control_panel/new_post.html",
                           form=form)

@control_panel.route("/cpanel/editpost", methods=["GET", "POST"])
@login_required
def edit_post():
    return "Not implemented"


@control_panel.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None or not user.verify_password(form.password.data):
            flash("Invalid email or password.")
            return redirect(url_for(".login"))
        login_user(user, form.remember_me.data)
        return redirect(request.args.get("next") or url_for("blogs.home"))
    return render_template("control_panel/login.html",
                           form=form
                           )


@control_panel.route("/logout", methods=["GET", "POST"])
@login_required
def logout():
    logout_user()
    flash("You have been logged out")
    return redirect(request.args.get("next") or url_for("blogs.home"))

blog/templates/control_panel/index.html
{% extends "base.html" %}

{% block page_content %}
<div class="row">
  <div class="container">
    <ul class="post-list">
      <li class="post-list-item">
        <div class="row">
          <div class="col-sm-9 col-xs-12">
            <strong>Blog Posts</strong>
          </div>
          <div class="col-sm-3 col-xs-12 text-right">
            <a class="btn btn-default btn-sm" href="{{ url_for("control_panel.new_post") }}">Write new post</a>
          </div>
        </div>
      </li>
    {% for post in posts %}
      <li class="post-list-item">
        <div class="container">
          <div class="row"><a href="{{ url_for("blogs.post", post_id=post.id) }}">{{ post.title }}</a></div>
          <div class="row">
            <a class="btn btn-default btn-xs" href="{{ url_for("control_panel.edit_post", id=post.id) }}">Edit</a>
            <a class="btn btn-default btn-xs" href="javascript:deletePost({{ post.id }});">Delete</a>
          </div>
        </div>
      </li>
    {% endfor %}
      
      
    {% set service_name = "blogs.post_list" %}
      <li class="post-list-item">
        <nav>
          <ul class="pagination pagination-sm">

            {% call pagination_post_list_side_item(page_num == 1 or page_total == 0, service_name, page_num - 1, "Previous", "<") %}
            {% endcall %}

            {% if page_total <= 10 %}
              {% for pg in range(page_total) %}
                {% call pagination_post_list_item(page_num, service_name, pg + 1) %}
                {% endcall %}
              {% endfor %}
            {% elif page_num < 5 %}
              {% for pg in range(10) %}
                {% call pagination_post_list_item(page_num, service_name, pg + 1) %}
                {% endcall %}
              {% endfor %}
            {% else %}
              {% for pg in range(page_total) %}
                {% call pagination_post_list_item(page_num, service_name, pg - 4) %}
                {% endcall %}
              {% endfor %}
            {% endif %}

            {% call pagination_post_list_side_item(page_num == page_total or page_total == 0, service_name, page_num + 1, "Next", ">") %}
            {% endcall %}

          </ul>
        </nav>
      </li>
    </ul>
  </div>
</div>
<div class="row">

</div>
{% endblock %}

blog/templates/control_panel/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="page-header">
  <h1>Login</h1>
</div>

{{ wtf.quick_form(form) }}
{% endblock %}

blog/templates/control_panel/message_page.html
{% extends "bootstrap/base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block body %}
<div class="container">
  <h2 class="text-center">{{ title }}</h2>
  <div>{{ message }}</div>
  <div class="text-center"><a href="{{ next_url }}">continue...</a></div>
</div>
{% endblock %}

blog/templates/control_panel/new_post.html
{% extends "base.html" %}

{% block head %}
{{ super() }}

{% endblock %}

{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<form method="POST" onsubmit="return verifyBlogBody()">
  <div id="wrapper" class="col-sm-12 col-md-8">
    <div id="title-field" class="form-group">
      {{ form.hidden_tag() }}

      <div class="form-group required">
        {{ form.title.label(class="control-label") }}
        {{ form.title(required="", class="form-control") }}
      </div>

      <div class="form-group">
        <label for="{{ form.body.name }}">{{ form.body.label }}</label>
        {{ form.body(rows=40, id="blog-body-input", class="form-control", style="resize: vertical") }}
      </div>

      <div class="form-group">
        <button type="button" class="btn btn-default text-center">
          <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> Preview
        </button>
      </div>

      <div class="form-group">
        <div id="preview-content">
        </div>
      </div>
      
      

      {{ wtf.form_errors(form, hiddens="only") }}
    </div>
  </div>
  <div id="sidebar" class="col-sm-12 col-md-4">
    <div class="sidebar-widget">
      <label>Actions</label>
      <div class="form-group">
        {{ form.draft(class="form-control btn btn-default") }}
      </div>
      <div class="form-group">
        {{ form.post(class="form-control btn btn-primary") }}
      </div>
    </div>
    <div class="sidebar-widget form-group">
      <label>Category</label>
    </div>
    <div class="sidebar-widget form-group">
      <label>Tags</label> 
    </div>
  </div>
</form>

<div class="modal fade" id="blog-body-helper">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Invalid Blog Body</h4>
      </div>
      <div class="modal-body">
        <p>The blog body is invalid.</p>
        <p>At first line, a block type is required, for example:</p>
        <pre>[[markdown]]</pre>
        <pre>[[html]]</pre>
        <pre>[[text]]</pre>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

{% endblock %}

blog/templates/control_panel/setup.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Setup Blog{% endblock %}

{% block body %}
<div class="container" >
  <h2 class="text-center" >Setup Blog</h2>
  {{ wtf.quick_form(form) }}
</div>
{% endblock %}

blog/templates/control_panel/success.html
{% extends "bootstrap/base.html" %}

{% block title %}Setup Success!{% endblock %}

{% block body %}Now you have all done!{% endblock %}